### PR TITLE
Dont crash because of to json

### PR DESCRIPTION
**Pull request by jiancheung**
searching `gearman-admin "Server listening on port 80 in production mode"` in splunk shows all the time gearman admin has crashed and it is all because of calling toJSON of undefined.

### CODE REVIEW

**Comment by jiancheung** [comment]
I think that trick existed before we used postgres so it was not safe to run multiple.  But currently we have 2 machines running it and both attached to elb so clearly it is okay to run multiple at a time (or we have been doing really bad things)

**Comment by azylman** [comment]
We use the CPU hack to make sure we have two machines for redundancy

**Comment by jiancheung** [comment]
@azylman if that is the case, why not just run 2 machines of 2 instances?

**Comment by jiancheung** [comment]
@jefff says it was because of sheer number of connection handles that the OS can handle.

**Comment by jefff** [comment]
lgtm.

**Pull request merged**
