### PR TITLE
default gearman workload to an empty string when re-running

### PR DESCRIPTION
**Pull request by natebrennand**
This fixes buggy behavior that re-posted a empty JSON payload instead of an empty string for jobs that have no payload.

### CODE REVIEW

**Comment by natebrennand** [comment]
CC @schimmy  & @azylman

**Comment by natebrennand** [comment]
Tested with locally by posting and reposting jobs, achieved the desired behavior which is:
- jobs with an empty body show up as an empty string
- reposted jobs with an empty body still have an empty body
- json workloads are still pretty printed

**Comment by johnhuangclever** [comment]
```
                                                                 ╖╖╖╖µ          
                                                                 ╙╢▒▓▓▓▒╦       
        ╓╦╣▒▓▒Θ⌐                                             ╔µ   ╠▒▓▓▓▓▓▓╕     
      ╔╣▒▓▓▓▓▌    ,                                         ╢╣░    ╚▒▓▓▓▓▓▓Q    
     ╢▒▓▓▓▓▓▒╜   ╠▒╦                                       -╫▒▓▒µ  '╢▓▓▓▓▓▓▓▌µ  
   ╓╣▒▓▓▓▓▓▒░   ╢▒▓▓╕                                      ░╫▒▓▓▒⌐  ]▒▓▓▓▓▓▓▓▒░ 
  '╢▓▓▓▓▓▓▓░   ╢▒▓▓▓░                                      ░╫▓▓▓▓▒µ ]▒▓▓▓▓▓▓▓▒░ 
  ¿╢▓▓▓▓▓▓▓▌⌐.╢▒▓▓▓▓░                                       ║▒▓▓▓▓▌░]▒▓▓▓▓▓▓▓Θ░ 
   ╠▓▓▓▓▓▓▓▌╓╣▓▓▓▓▓▒                                        "╫▓▓▓▓▓▌╠▒▓▓▓▓▓▓▒░  
   ╠▓▓▓▓▓▓▓▓╣▓▓▓▓▓▒'           -╖╖-        -╖╥╥╖⌐            ░▒▓▓▓▓▓▓▓▓▓▓▓▓▓▌   
   ]╫▓▓▓▓▓▓▓▓▓▓▓▓▒░          -'░╫▓▓▓╣░   -░░░▒▓▓▓╦            ╙▒▓▓▓▓▓▓▓▓▓▓▓▓▓░  
   ░▒╣▒▓▓▓▓▓▓▓▓▓▒░          ]╣╣▒▓▓▓▓▓▒░  ╠▒▒▓▓▓▓▓▓░            ╠▒▒▒▓▓▓▓▓▓▓▓▓▓░  
   ░▒▒▓▓▓▓▓▓▓▓▓▓Θ           ]▒▓▓▓▓▓▓▓Θ░  ░▒▓▓▓▓▓▓▒░            ]▒▒▓▓▓▓▓▓▓▓▓▓▌░  
    ░▒▓▓▓▓▓▓▓▓▓▒░            ╙Θ▒▓▓▓█Θ░    ╙Θ▒▓▓█Θ░░            '╠▒▓▓▓▓▓▓▓▓▓▓░   
     ╠▒▓▓▓▓▓▓▓▓Θ⌐             ░░░░░╥░⌐     '░╖╖╥╥░              ╠▒▓▓▓▓▓▓▓▓▓░    
      ╚▒▓▓▓▓▓▓▓░               ╙╢▒▓╣░▄╖╖╥╥▄-╓▒▓▒░              !╠▒▓▓▓▓▓▓▓█╨     
       ░▒▒▓▓▓▓▓▒⌐              ╔╣▓▓▓▓▒▒▒▓▓▓▓▓▓▓▓╦µ             '╢▒▒▓▓▓▓▓Ö       
        ╙δ▒▓▓▓▀             ╥╣▒▓▓▓▓▓▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓▄╦            ╙▒▓▓▓Θ╜        
          ╢▓▓▌           ╔╣▒▓▓▒▓▓▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▄µ         .╫▓▓Θ          
          ╙╢▓▓▒╕       ╓╣▓▓▒▒▒ΘΘΘδδδÜδÉδΘΘδδδΘΘΘΘ▒▒▓▓▓▓▓▄µ      ,╫▓▓▒⌐          
           ╙╢▓▓▓Q,   ╓╣▓▓▓▒░░          '░⌐ ⌐⌐░░░░░░░╢▓▓▓▓▓▄   ,╥▒▓▓▒░           
             ╙Θ▓▓▓▒╦╗▒▓▓▓▒▒▒▒▒▄╦╤╦╖╖-╖╖░░░░░░░╣╣╣╣╣▒▓▓▓▓▓▓▓▓╦╣▒▓▓Θ╜             
               '╙Θ▒▓▓▓▓▓▓▓▓▒▒▒▒▒▓▓▓▒▒▒▒▒▒▒▒▒▒▓▓▓▓▒▒▒▒▓▓▓▓▓▓▓▓▓█▀                
                 .╠▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░╢▒▓▓▓▓▓▓▓░                 
                 ╠▓▓▓▓▓▓▒░░░░░░░░░░░░░░░░░░░░░░░░╢░░░░░╢▒▓▓▓▓▓▌░                
                -░ΘΘΘΘΘ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╢╢▒███▒░░--             
         ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╣░░░░░░░░░░░░░░░░░░░░░░░░░░'  ░⌐        
        '░░░░""""╚╢▒╣╣╣╣╣Θ░░░░╢╣╣░░░░░░░░░░░░░╢╣╣░░░░░░░╣╣╦╣╣╣░      '░░░⌐      
      '░░░░       ░░░░░░░░░░░░░░░░░░░░░░░░░░░░╢░░░░░░░░░░░░░░░░░      ░░░░⌐     
      ░░░░░  ░░░░░░░░░░░░░░░░░░╢░░░╢░░░░░░░░╣╣╣╣╣░░░░░░░░░░░░░░░' ░⌐  ░░░░░     
     ░░░░░  ░░░"""'   ░░░░░░╦╣╣░░░░░░░░░░░░╣╣╣╣╣╣╣╣╣░░░░░░░░      "░░ ░░░╣░⌐    
    '░░░░ -░░░    -░░╙╨░'  "╙ÉÉδ░░δ░░░░░░░░δΘΘΘΘΘΘΘΘΘÉ░    '░░⌐    ░░░ ░╢╣░░    
    ░░░░  ░░░    ░░'                                         ░░░   '░░⌐ ░╢░░    
     ░░   ░░    ░░                                            "░░   "░░  '░░    
    !░░  '░⌐    '                                                    ░░  '░░    
     ╙░                                                                  ░░     
```

**Comment by ericavonb** [comment]
@natebrennand is there anything stopping us from rolling this out?

**Comment by natebrennand** [comment]
I previously didn't have bandwidth to monitor on launch, will do so now.

**Pull request merged**
