### PR TITLE
package.json: add --nodejs flag to npm start command

### PR DESCRIPTION
**Pull request by peggyl**
Fix broken deploy from #110 

```
            throw new Error("unrecognized option: " + arg);
            ^

Error: unrecognized option: --max_old_space_size=500
```

### CODE REVIEW

**Comment by peggyl** [comment]
https://github.com/Clever/gearman-admin/pull/110#discussion_r87057857

**Comment by peggyl** [comment]
Sorry, just realized a comment on the previous PR got hidden during a force push. I can s/500/512/ if you want, but I saw 1000 instead of 1024 in the oauth example.

**Comment by natebrennand** [comment]
I don't think the 500 or 512 bit matters much

**Comment by peggyl** [comment]
`npm start` gets further than the unrecognized option error but instead I'm seeing

```
(node:20987) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
unrecognized database type undefined, defaulting to postgres
SyntaxError: Unexpected token u in JSON at position 0
```

Not sure if this is an issue in my environment, can try deploying to staging to be sure.

**Comment by peggyl** [comment]
Deploy in staging to sanity-check, after omitting that step last PR led to bad outcomes… 😞

**Comment by peggyl** [comment]
Staging deploy seems fine based on logs and ability to access web interface.

**Pull request merged**
