### PR TITLE
build a docker image on every commit

### PR DESCRIPTION
**Pull request by azylman**

### CODE REVIEW

**Comment by azylman** [comment]
@schimmy after this, I'm going to change https://github.com/Clever/gearman-admin/pull/46 to make SIGTERM wait until the instance is tracking no jobs to stop. Then we can merge in the redis stuff, and then we're done :)

**Comment by azylman** [comment]
cc: @mohit

**Comment by mohit** [comment]
'health_check' in launch.yml might be useful for gearman-admin. See clever-api launch file.

**Comment by schimmy** [comment]
LGTM!

**Pull request merged**
